### ISSUE TITLE
Panic when running preset Alignment

### ISSUE THREAD

**Issue by smousa** [MaxHalford/gago#2]
Maybe you can tell me if I am doing something wrong here?  All the code is doing is initializing the preset.

```
panic: invalid argument to Intn

goroutine 6 [running]:
panic(0x4c88c0, 0xc42000a870)
	~/.gvm/gos/go1.7.1/src/runtime/panic.go:500 +0x1a1
math/rand.(*Rand).Intn(0xc42000e5c0, 0x0, 0xc42000a866)
	~/.gvm/gos/go1.7.1/src/math/rand/rand.go:116 +0xd0
github.com/MaxHalford/gago.InitUniformS.Apply(0x589780, 0x0, 0x0, 0xc42007c000, 0xc42000e5c0)
	~/.gvm/pkgsets/go1.7.1/global/src/github.com/MaxHalford/gago/initializing.go:52 +0x57
github.com/MaxHalford/gago.(*InitUniformS).Apply(0xc42000e5a0, 0xc42007c000, 0xc42000e5c0)
	<autogenerated>:26 +0x78
github.com/MaxHalford/gago.makePopulation(0x1e, 0x12, 0x55a540, 0xc420010210, 0x55a440, 0xc42000e5a0, 0x0, 0x0, 0x0, 0x0, ...)
	~/.gvm/pkgsets/go1.7.1/global/src/github.com/MaxHalford/gago/population.go:30 +0x1e1
github.com/MaxHalford/gago.(*GA).Initialize.func1(0xc42000a680, 0xc42005aa90, 0x1)
	~/.gvm/pkgsets/go1.7.1/global/src/github.com/MaxHalford/gago/ga.go:95 +0x9f
created by github.com/MaxHalford/gago.(*GA).Initialize
	~/.gvm/pkgsets/go1.7.1/global/src/github.com/MaxHalford/gago/ga.go:100 +0x144
```

**Comment by smousa** [comment]
I figured it out.  I was passing zero into Corpus
